build_react:
    image: mhart/alpine-node:latest
    stage: deploy 
    script: 
        - yarn 
        - CI=false yarn build
        - cp public/.htaccess build
        - apk add --no-cache rsync openssh
        - mkdir -p ~/.ssh
        - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
        - chmod 600 ~/.ssh/id_dsa
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - rsync -rav --delete build/  $SERVER_CONN:$PROJECT_FOLDER
    only:
        - main
