export const GET_TOP_PODCASTS = 'GET_TOP_PODCASTS';
export const GET_PODCAST_DETAIL = 'GET_PODCAST_DETAIL';
export const PLAY_PODCAST_ITEM = 'PLAY_PODCAST_ITEM';
export const GET_FAVORITES = 'GET_FAVORITES';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const SEARCH = 'SEARCH';
export const RESET_PODCASTS = 'RESET_PODCASTS';
